# Generated by Django 4.2.13 on 2024-05-22 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='fecha_inicio',
            new_name='fecha_alta',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='fecha_fin',
            new_name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='telefono',
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrera',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Previas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='domain.curso')),
                ('previa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previa', to='domain.curso')),
            ],
        ),
        migrations.CreateModel(
            name='BloqueDeClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField()),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingos')], max_length=500)),
                ('duracion', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('alumnos_cursos', models.ManyToManyField(to='domain.alumnocurso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.curso')),
                ('profesores', models.ManyToManyField(to='domain.profesor')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('temario', models.TextField()),
                ('alumnos', models.ManyToManyField(to='domain.alumno')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.bloquedeclase')),
                ('profesores', models.ManyToManyField(to='domain.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.alumno'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.curso'),
        ),
        migrations.CreateModel(
            name='AlumnoCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizado', models.DateTimeField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.carrera')),
            ],
        ),
    ]
