# Generated by Django 4.2.13 on 2024-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='costo',
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
