# Generated by Django 4.2.13 on 2024-05-26 01:35

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_profesor_activo_profesor_apellido_profesor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254, validators=[utils.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, validators=[utils.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
