# Generated by Django 4.2.13 on 2024-05-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_alumno_email_alter_alumno_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('alumnos', models.ManyToManyField(to='domain.alumno')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.bloquedeclase')),
                ('profesores', models.ManyToManyField(to='domain.profesor')),
            ],
        ),
        migrations.RenameModel(
            old_name='Previas',
            new_name='Previa',
        ),
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
