# Generated by Django 4.2.13 on 2024-05-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_salon_descripcion_alter_salon_capacidad'),
        ('domain', '0005_alter_carrera_fecha_alta'),
    ]

    operations = [
    ]
