# Generated by Django 4.2.13 on 2024-05-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0006_merge_20240530_0953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="fecha_fin",
        ),
    ]
