# Generated by Django 4.2.13 on 2024-05-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_remove_profesor_cursos'),
        ('profiles', '0002_alumno_profesor_delete_principalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnocarrera',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.alumno'),
        ),
        migrations.AlterField(
            model_name='alumnocurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.alumno'),
        ),
        migrations.AlterField(
            model_name='bloquedeclase',
            name='profesores',
            field=models.ManyToManyField(to='profiles.profesor'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='alumnos',
            field=models.ManyToManyField(to='profiles.alumno'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='profesores',
            field=models.ManyToManyField(to='profiles.profesor'),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
