# Generated by Django 4.2.13 on 2024-06-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alumno_user_profesor_user'),
        ('domain', '0007_remove_curso_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingos')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='alumnos_cursos',
        ),
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='cupo',
        ),
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='bloquedeclase',
            name='dia',
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField()),
                ('alumnos', models.ManyToManyField(blank=True, null=True, to='profiles.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.curso')),
                ('profesores', models.ManyToManyField(to='profiles.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='bloquedeclase',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.grupo'),
        ),
        migrations.AddField(
            model_name='bloquedeclase',
            name='dia',
            field=models.ManyToManyField(to='domain.dia'),
        ),
    ]
