# Generated by Django 4.2.13 on 2024-06-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0008_dia_remove_bloquedeclase_alumnos_cursos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dia",
            name="name",
            field=models.CharField(
                choices=[
                    ("LUN", "Lunes"),
                    ("MAR", "Martes"),
                    ("MIE", "Miércoles"),
                    ("JUE", "Jueves"),
                    ("VIE", "Viernes"),
                    ("SAB", "Sábado"),
                    ("DOM", "Domingos"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="alumnos",
            field=models.ManyToManyField(blank=True, to="profiles.alumno"),
        ),
    ]
