# Generated by Django 4.2.13 on 2024-06-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0014_alter_curso_payout_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="identificador",
            field=models.CharField(default="A", max_length=1),
            preserve_default=False,
        ),
    ]
