# Generated by Django 4.2.13 on 2024-06-12 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0015_grupo_identificador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salon",
            name="capacidad",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "La capacidad debe ser mayor o igual a 1."
                    ),
                    django.core.validators.MaxValueValidator(
                        500, "La capacidad debe ser menor o igual a 500."
                    ),
                ],
            ),
        ),
    ]
