# Generated by Django 4.2.13 on 2024-07-06 21:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0016_pago"),
        ("domain", "0017_alter_salon_nombre"),
    ]

    operations = []
