# Generated by Django 4.2.13 on 2024-06-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0018_alumnocarrera_fecha_baja_alumnocurso_fecha_baja_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumnocurso",
            options={"ordering": ["-fecha_inscripcion"]},
        ),
    ]
