# Generated by Django 4.2.13 on 2024-06-21 20:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0020_examen"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumnoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fallo",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                10, "La nota máxima permitida es 10."
                            ),
                            django.core.validators.MinValueValidator(
                                1, "La nota mínima permitida es 1."
                            ),
                        ],
                    ),
                ),
                ("comentario", models.TextField(blank=True, max_length=250, null=True)),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="domain.examen"
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="domain.alumnocurso",
                    ),
                ),
            ],
        ),
    ]
