# Generated by Django 4.2.13 on 2024-07-09 00:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0018_merge_0016_pago_0017_alter_salon_nombre"),
        ("domain", "0022_alter_alumnoexamen_options_alter_examen_options_and_more"),
    ]

    operations = []
