# Generated by Django 4.2.13 on 2024-07-10 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0019_alter_grupo_cupo"),
        ("domain", "0022_alter_alumnoexamen_options_alter_examen_options_and_more"),
    ]

    operations = []
