# Generated by Django 4.2.13 on 2024-07-13 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0023_merge_20240708_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="domain.curso",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="comprobante",
            field=models.FileField(blank=True, null=True, upload_to="pagos"),
        ),
    ]
