# Generated by Django 4.2.13 on 2024-07-21 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0023_merge_20240709_2319"),
        ("domain", "0024_pago_curso_alter_pago_comprobante"),
    ]

    operations = []
