# Generated by Django 4.2.13 on 2024-07-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0025_merge_20240721_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
