# Generated by Django 4.2.13 on 2024-07-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0025_merge_20240718_1138'),
        ('domain', '0028_alter_dia_id'),
    ]

    operations = [
    ]
