# Generated by Django 4.2.13 on 2024-07-29 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0030_alter_bloquedeclase_id_alter_pago_monto"),
        ("domain", "0030_alter_pago_monto"),
    ]

    operations = []
