# Generated by Django 4.2.13 on 2024-07-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0030_alter_bloquedeclase_id_alter_pago_monto'),
        ('domain', '0030_alter_pago_monto'),
    ]

    operations = [
    ]
