# Generated by Django 4.2.13 on 2024-07-31 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0031_merge_20240729_1859"),
        ("domain", "0031_merge_20240730_2212"),
    ]

    operations = []
