# Generated by Django 4.2.13 on 2024-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0032_merge_20240731_2027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pago",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
