# Generated by Django 4.2.13 on 2024-08-06 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0033_alter_pago_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnocurso",
            name="fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=7,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "La cuota real debe ser mayor a 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        50000, "La cuota real debe ser menor a $50000."
                    ),
                ],
            ),
        ),
    ]
