# Generated by Django 4.2.13 on 2024-08-05 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0033_alter_pago_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="fecha_baja",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grupo",
            name="fecha_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
