# Generated by Django 4.2.13 on 2024-08-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0034_grupo_activo_grupo_fecha_baja_grupo_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
