# Generated by Django 4.2.13 on 2024-08-05 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0035_remove_grupo_identificador_alter_grupo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="fecha_baja",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="fecha_inicio",
            field=models.DateField(default=datetime.date(2024, 8, 5)),
        ),
    ]
