# Generated by Django 4.2.13 on 2024-08-05 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0036_alter_grupo_fecha_baja_alter_grupo_fecha_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="fecha_baja",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grupo",
            name="fecha_inicio",
            field=models.DateTimeField(default=datetime.date(2024, 8, 5)),
        ),
    ]
