# Generated by Django 4.2.13 on 2024-08-06 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0034_alumnocurso_fee"),
        ("domain", "0037_alter_grupo_fecha_baja_alter_grupo_fecha_inicio"),
    ]

    operations = []
