# Generated by Django 4.2.13 on 2024-08-07 21:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0038_merge_20240807_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.date(2024, 8, 7)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
