# Generated by Django 4.2.13 on 2024-08-07 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0040_faltaprofesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faltaprofesor',
            old_name='Grupo',
            new_name='grupo',
        ),
        migrations.RenameField(
            model_name='faltaprofesor',
            old_name='profesor_faltante',
            new_name='profesor_titular',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
