# Generated by Django 4.2.13 on 2024-08-08 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0041_merge_20240808_1852"),
        ("domain", "0041_rename_grupo_faltaprofesor_grupo_and_more"),
    ]

    operations = []
