# Generated by Django 4.2.13 on 2024-08-12 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0041_merge_20240808_1852"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="fecha_inicio",
            field=models.DateTimeField(default=datetime.date(2024, 8, 12)),
        ),
    ]
