# Generated by Django 4.2.13 on 2024-08-12 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0043_alter_faltaprofesor_profesor_suplente_and_more"),
        ("domain", "0043_grupo_identificador"),
    ]

    operations = []
