# Generated by Django 4.2.13 on 2024-08-12 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domain", "0038_merge_20240806_2029"),
        ("domain", "0044_merge_20240812_2036"),
    ]

    operations = []
