# Generated by Django 4.2.13 on 2024-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alumno_user_profesor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="code",
            field=models.CharField(default="ABCDEFGH", max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profesor",
            name="code",
            field=models.CharField(default="ABCDEFGH", max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
