# Generated by Django 4.2.13 on 2024-06-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alumno_code_profesor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
