# Generated by Django 4.2.13 on 2024-06-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_alter_profesor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="M",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profesor",
            name="sexo",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="M",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
