# Generated by Django 4.2.13 on 2024-08-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_alumno_sexo_profesor_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
