# Generated by Django 4.2.13 on 2024-08-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_alumno_emergency_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="direccion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="direccion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
