# Generated by Django 4.2.13 on 2024-08-12 17:53

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_alumno_direccion_alter_profesor_direccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[utils.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[utils.validators.EmailValidator()],
            ),
        ),
    ]
